#!/usr/bin/env python
# -*- coding: utf-8 -*-

# gm-notify-config v0.10.3
# GMail Notifier Configuration Utility
#
# Copyright (c) 2009-2010, Alexander Hungenberg <alexander.hungenberg@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from __future__ import print_function

import sys
import os
import gettext
import subprocess
import shutil

from gi.repository import Gio, Gtk

from twisted.internet import gtk3reactor
gtk3reactor.install()
from twisted.internet import reactor
from twisted.words.protocols.jabber import jid

import gm_notify_keyring as keyring
from gtalk import MailChecker
from settings_provider import SettingsProvider

_ = gettext.translation('gm-notify', fallback=True).ugettext

class PathNotFound(Exception): pass

def get_executable_path(name):
    path = "%s/%s" % (os.getcwd(), name)
    if os.path.exists(path) and os.access(path, os.X_OK): return path
    path = "/usr/local/bin/" + name
    if os.path.exists(path) and os.access(path, os.X_OK): return path
    path = "/usr/bin/" + name
    if os.path.exists(path) and os.access(path, os.X_OK): return path
    raise PathNotFound("%s not found" % name)

class Window(Gtk.Application):
    def __init__(self):
        super(Window, self).__init__(application_id="net.launchpad.gm-notify-config",
            flags=Gio.ApplicationFlags.FLAGS_NONE)
        self.window = None
        self.connect("activate", self.on_activate)

    def on_activate(self, app):
        '''Setup the application'''
        if self.window is not None:
            return

        #####
        # GUI initialization
        #####
        self.keys = keyring.Keyring("GMail", "mail.google.com", "http")
        self.client = SettingsProvider()
        
        if os.path.exists("gm-config.ui"):
            builder_file = "gm-config.ui"
        elif os.path.exists("/usr/local/share/gm-notify/gm-config.ui"):
            builder_file = "/usr/local/share/gm-notify/gm-config.ui"
        elif os.path.exists("/usr/share/gm-notify/gm-config.ui"):
            builder_file = "/usr/share/gm-notify/gm-config.ui"

        self.wTree = Gtk.Builder.new()
        self.wTree.add_from_file(builder_file)
        self.wTree.set_translation_domain("gm-notify")
        self.window = self.wTree.get_object("gmnotify_config_main")
        self.window.show_all()
        self.add_window(self.window)

        self.wTree.get_object("notebook_main").set_current_page(0)
        
        self.input_user = self.wTree.get_object("input_user")
        self.input_password = self.wTree.get_object("input_password")
        self.image_credentials = self.wTree.get_object("image_credentials")
        self.label_credentials = self.wTree.get_object("label_credentials")
        self.button_apply = self.wTree.get_object("button_apply")
        
        #####
        # Init with stored values
        #####
        
        # Credentials
        if self.keys.has_credentials():
            self.creds = self.keys.get_credentials()
        else:
            self.creds = ("", "")
        self.input_user.set_text(self.creds[0])
        self.input_password.set_text(self.creds[1])
        
        self.api = MailChecker("", "", self.client)
        self.api.setOnAuthSucceeded(self.credentials_valid)
        self.api.setOnAuthFailed(self.credentials_invalid)
        self.api.setOnConnectionErrorCB(self.connection_error)
        
        self.check_credentials(None, None)
        
        # Sound
        self.wTree.get_object("checkbutton_sound").set_active(self.client.retrieve_sound_enabled())
        sound_file = self.client.retrieve_sound_file()
        if sound_file:
            self.wTree.get_object("fcbutton_sound").set_filename(sound_file)
        self.on_checkbutton_sound_toggled(self.wTree.get_object("checkbutton_sound"))
        
        # ClickAction
        if self.client.retrieve_use_mail_client():
            self.wTree.get_object("radiobutton_openclient").set_active(True)
        else:
            self.wTree.get_object("radiobutton_openweb").set_active(True)
        
        # Mailboxes
        self.wTree.get_object("checkbutton_inbox").set_active(self.client.retrieve_ignore_inbox())
        mailboxes = self.client.retrieve_mailboxes()
        self.wTree.get_object("entry_labels").set_text(", ".join(mailboxes))

        # Autorun
        if os.path.exists("data/gm-notify.desktop"):
            self.gm_notify_autostart_file = "data/gm-notify.desktop"
        elif os.path.exists("/usr/local/share/applications/gm-notify.desktop"):
            self.gm_notify_autostart_file = "/usr/local/share/applications/gm-notify.desktop"
        elif os.path.exists("/usr/share/applications/gm-notify.desktop"):
            self.gm_notify_autostart_file = "/usr/share/applications/gm-notify.desktop"
        self.autostart_file = os.path.expanduser("~/.config/autostart/gm-notify.desktop")
        self.wTree.get_object("checkbutton_autostart").set_active(os.path.exists(self.autostart_file))
        
        # Connect signals
        self.wTree.get_object("button_close").connect("clicked", self.terminate)
        self.button_apply.connect("clicked", self.save)
        self.input_password.connect("focus-out-event", self.check_credentials)
        self.wTree.get_object("checkbutton_sound").connect("toggled", self.on_checkbutton_sound_toggled)
    
    def save(self, widget, data=None):
        '''saves the entered data and closes the app'''
        # Credentials
        self.keys.delete_credentials()
        self.keys.set_credentials(self.input_user.get_text(),
                                  self.input_password.get_text())
        
        # Mailboxes
        mailboxes = []
        for label in self.wTree.get_object("entry_labels").get_text().split(","):
            mailboxes.append(label.strip())
        self.client.save_mailboxes(mailboxes)
        self.client.save_ignore_inbox(self.wTree.get_object("checkbutton_inbox").get_active())
        
        # ClickAction
        self.client.save_use_mail_client(self.wTree.get_object("radiobutton_openclient").get_active())

        # Soundfile
        if self.wTree.get_object("checkbutton_sound").get_active() and self.wTree.get_object("fcbutton_sound").get_filename():
            self.client.save_sound_enabled(True)
            self.client.save_sound_file(str(self.wTree.get_object("fcbutton_sound").get_filename()))
        else:
            self.client.save_sound_enabled(False)

        # Autorun
        if self.wTree.get_object("checkbutton_autostart").get_active():
            if not os.path.exists(self.autostart_file):
                try:
                    os.makedirs(os.path.expanduser("~/.config/autostart"))
                except OSError:
                    pass

                try:
                    shutil.copyfile(self.gm_notify_autostart_file, self.autostart_file)
                    os.chmod(self.autostart_file, 0700)
                except IOError:
                    print("Warning: cannot write to path", self.autostart_file)
        else:
            if os.path.exists(self.autostart_file):
                try:
                    os.unlink(self.autostart_file)
                except:
                    print("Warning: cannot delete", self.autostart_file)

        # Start gm-notify itself
        subprocess.Popen(get_executable_path("gm-notify"))
    
    def terminate(self, widget):
        reactor.stop()
    
    def on_checkbutton_sound_toggled(self, widget):
        self.wTree.get_object("fcbutton_sound").set_sensitive(self.wTree.get_object("checkbutton_sound").get_active())
    
    def check_credentials(self, widget, event, data=None):
        '''check if the given credentials are valid'''
        
        self.button_apply.set_sensitive(False)
        
        # Change status text and disable input fields
        if self.input_user.get_text() and self.input_password.get_text():
            self.image_credentials.set_from_file("/usr/share/gm-notify/checking.gif")
            self.label_credentials.set_text(_("checking..."))
            self.input_user.set_sensitive(False)
            self.input_password.set_sensitive(False)
            
            self.api.jid = jid.JID(self.input_user.get_text())
            self.api.password = self.input_password.get_text()
            self.api.connect()
        return False
    
    def credentials_valid(self):
        self.on_credentials_checked("gtk-yes", "Valid credentials", True)

    def credentials_invalid(self):
        self.on_credentials_checked("gtk-stop", "Invalid credentials")
        
    def connection_error(self, reason):
        self.on_credentials_checked("gtk-stop", "Connection error")
        
    def on_credentials_checked(self, icon_name, text, valid = False):
        self.image_credentials.set_from_icon_name(icon_name, Gtk.IconSize.MENU)
        self.label_credentials.set_text(_(text))
        self.input_user.set_sensitive(True)
        self.input_password.set_sensitive(True)
        self.button_apply.set_sensitive(valid)

        self.api.die()

t = Window()
reactor.registerGApplication(t)
reactor.run()
